### PR TITLE
Belongs to polymorphic options

### PR DESCRIPTION
**Pull request by tristil**
Rebased version of https://github.com/wegowise/polymorpheus/pull/19

Very small changes to @randoum 's original commit:

- squashed the commits
- renamed Draw model to Drawing
- added comment to README about additional options

### CODE REVIEW

**Comment by tristil** [comment]
@barunio This is ready to merge. Are you okay with this? One emoji is enough IMO.

**Comment by barunio** [comment]
I'd like to see some documentation change to reflect this code change (perhaps on the Wiki page). Also, I'm not sure what the Travis config setup change does -- can you explain in the commit message? Other than that, :rabbit: :rabbit2:

**Comment by tristil** [comment]
I added some inline comments to the code examples on the README page just saying that `has_many_as_polymorph` and `belongs_to_polymorphic` take the same options as their corresponding AR associations.

I added an explanation of the Travis CI change.

**Comment by tristil** [comment]
@randoum Thanks for this change! We'll be cutting a new gem soon.

**Comment by tristil** [comment]
New gem version 3.1.0 pushed

**Comment by randoum** [comment]
Awesome! Sorry I could not help for the rebase

**Pull request merged**
